services:
  graphite:
    image: graphiteapp/graphite-statsd:1.1.10-5
    restart: unless-stopped
    networks:
      - metrics-network
    healthcheck:
      test: [ "CMD", "nc", "-zv", "localhost", "8126" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 1m
    volumes:
      - ./graphite/storage:/opt/graphite/storage
    ports:
      - '8125:8125/udp' # statsd udp
      - '80:80' # graphite web interface (debug only)
    environment:
      - STATSD_INTERFACE=udp
      - STATSD_PORT=8125

  grafana:
    image: grafana/grafana:10.0.3
    restart: unless-stopped
    networks:
      - metrics-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "localhost:3000/api/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 1m
    volumes:
      - ../grafana:/etc/grafana
      - ../grafana/data:/var/lib/grafana
    ports:
      - '3000:3000'

networks:
  metrics-network:
    driver: bridge