name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"
  SQLX_OFFLINE: true

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: waypoint
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Install protoc and database clients
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler redis-tools postgresql-client

    - name: Verify Redis Connection
      run: redis-cli ping

    - name: Verify Postgres Connection
      run: pg_isready -h localhost -p 5432

    - name: Init postgres schema
      run: psql -h localhost -p 5432 -U postgres -d waypoint -f migrations/init.sql
      env:
        PGPASSWORD: postgres

    - name: Install Rust
      uses: dtolnay/rust-toolchain@1.85.0

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2

    - name: Build
      run: make build
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/waypoint

    - name: Run tests
      run: cargo test --verbose
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/waypoint
        REDIS_URL: redis://localhost:6379
